spring:
  application:
    name: ifone_spring_external_service

  datasource:
    url: jdbc:postgresql://localhost:5432/ifone_prescriptions
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8086

gemini:
  model: gemini-2.0-flash-lite

aws:
  s3:
    bucket:
      name: your_bucket_name
      region: your_region

app:
  paths:
    sow: document_downloads/
    prescription_uploads: prescription_uploads/